-- AlterTable
ALTER TABLE "ESTest" ADD COLUMN IF NOT EXISTS "releaseScoresAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "scoreReleaseMode" "ScoreReleaseMode" NOT NULL DEFAULT 'FULL_TEST',
ADD COLUMN IF NOT EXISTS "scoresReleased" BOOLEAN NOT NULL DEFAULT false;
